import { CHAIN_V1_FIXTURE } from './chain-v1-fixture.js'

/**
 * The chain fixture in the BSV stack's cross-language conformance vector format
 * (`conformance/VECTOR-FORMAT.md` in bsv-blockchain/ts-stack), as a pure mapping
 * from the bespoke object. `fixtures/vectors/dpp/chain/v1.json` is this
 * function's output, verbatim, and `fixture-json.test.ts` holds the two
 * identical, so the chain is the first fixture whose two forms are both
 * generated by tests (`fixtures/README.md`, "Two forms, one set of bytes").
 *
 * The vectors publish the test private keys so a writer in any language
 * reproduces the pinned bytes rather than only checking them. Vector identifiers
 * are permanent once published and the file is append-only: a corrected
 * expectation is a new vector, never an edit.
 */
const PRIVATE_KEYS: Record<string, string> = {
  maker: '11'.repeat(32),
  server: '22'.repeat(32),
  owner1: '33'.repeat(32),
  owner2: '44'.repeat(32),
  owner3: '55'.repeat(32),
}

const STATE_DESCRIPTIONS = [
  'Genesis: ACTIVATE by the maker, locked to the maker. Sign the twelve data fields as actor and as service, then build the fourteen-field script and the one-output transaction (spec record-model.md sections 2, 5 and 6).',
  'SOLD by the maker, spending the genesis output. The DPP output sits at index 1 behind an OP_RETURN, so a reader tracks the outpoint rather than assuming index 0. Ownership does not move on SOLD.',
  'TRANSFER to the second owner, signed by the first owner. Field 7 equals the previous field 6, which is the equality form of the owner-signed transfer (spec custody.md section 4) although nothing in the first four states depends on the option.',
  'REPAIRED by the second owner: event_data carries the operation metadata, payload and owner unchanged.',
  "TRANSFER by the second owner to the third owner's per-passport owner key, derived from the third owner's root under [1, 'dpp owner v1'] with the passport identifier as key identifier and counterparty self (spec record-model.md section 3). The output is locked to that same key: the possession convention (spec custody.md section 3). Field 7 equals the previous field 6: the equality form of consent.",
  "TRANSFER by the third owner, acting under their root, to the first owner's per-passport owner key, again locked to it. event_data carries owner_linkage, the BRC-69 specific key linkage such that the previous field 6 equals field 7 plus owner_linkage times G: the linkage form of consent. The input is spent by the third owner's wallet through the PushDrop unlock under the owner protocol, one derivation and no key export; RFC 6979 nonces make the unlocking script reproducible.",
]

const kebab = (name: string): string => name.replace(/[A-Z]/g, (c) => '-' + c.toLowerCase())

export function chainV1Vectors(F: typeof CHAIN_V1_FIXTURE = CHAIN_V1_FIXTURE) {
  const stateVectors = F.states.map((s, i) => {
    const prev = i === 0 ? undefined : F.states[i - 1]
    return {
      id: `state-${i + 1}-${s.data.op.toLowerCase()}${s.unlock === 'owner' ? '-linked' : ''}`,
      description: STATE_DESCRIPTIONS[i],
      input: {
        data: s.data,
        actor_private_key_hex: PRIVATE_KEYS[s.actor],
        server_private_key_hex: PRIVATE_KEYS.server,
        locking_key_hex: s.lockingKey,
        ...(prev == null
          ? {}
          : { previous_raw_tx_hex: prev.rawTx, previous_output_index: prev.outputIndex }),
        op_return_first: s.outputIndex === 1,
        unlock: s.unlock,
        ...(s.unlock === 'owner'
          ? { unlock_protocol: F.ownerProtocol, unlock_key_id: s.data.passportId, unlock_counterparty: 'self' }
          : {}),
        signature_nonce: 'rfc6979',
      },
      expected: {
        user_signature_hex: s.userSignature,
        server_signature_hex: s.serverSignature,
        locking_script_hex: s.lockingScript,
        output_index: s.outputIndex,
        txid_hex: s.txid,
        raw_tx_hex: s.rawTx,
      },
      tags: ['happy-path', 'brc-42', 'brc-43', 'brc-48'],
    }
  })

  const ownerKeyVectors = [
    {
      id: 'owner-key-owner3',
      description:
        "The third owner's per-passport owner key and its linkage scalar (spec record-model.md section 3, spec custody.md sections 2 and 4). The key is the root derived under the owner protocol with the passport identifier as key identifier and counterparty self; the scalar is the BRC-42 HMAC for that derivation, which only the root can compute, and owner_key = root_public_key + linkage times G, which anyone can check.",
      input: {
        root_private_key_hex: PRIVATE_KEYS.owner3,
        passport_id: F.states[0].data.passportId,
        protocol: F.ownerProtocol,
        counterparty: 'self',
      },
      expected: {
        root_public_key_hex: F.owner3Key,
        owner_key_hex: F.owner3OwnerKey,
        linkage_hex: F.owner3OwnerLinkage,
        linkage_verifies: true,
      },
      tags: ['happy-path', 'brc-42', 'brc-43'],
    },
    {
      id: 'owner-key-owner1',
      description: "The first owner's per-passport owner key, the field 6 the sixth state transfers to, from the same derivation.",
      input: {
        root_private_key_hex: PRIVATE_KEYS.owner1,
        passport_id: F.states[0].data.passportId,
        protocol: F.ownerProtocol,
        counterparty: 'self',
      },
      expected: {
        root_public_key_hex: F.owner1Key,
        owner_key_hex: F.owner1OwnerKey,
      },
      tags: ['happy-path', 'brc-42', 'brc-43'],
    },
  ]

  const verifyVector = {
    id: 'verify-chain',
    description:
      'Verify the six raw transactions as a chain, genesis to tip, with the owner-signed transfer selected and no header source: every user signature verifies, every link holds, every server signature verifies under the service key, inclusion is pending, and the owner-signed transfer holds on the three TRANSFER states and is not applicable elsewhere (null). Scripts are not run by the verifier; the network ran them.',
    input: {
      raw_tx_hex: F.states.map((s) => s.rawTx),
      server_identity_key_hex: F.serverKey,
      owner_consent: true,
    },
    expected: {
      valid: true,
      spv: 'pending',
      states: F.states.map((s) => ({
        op: s.data.op,
        user_signature_valid: true,
        server_signature_valid: true,
        linkage_valid: true,
        owner_consent_valid: s.data.op === 'TRANSFER' ? true : null,
      })),
    },
    tags: ['happy-path', 'brc-42', 'brc-43'],
  }

  const refusalVectors = F.refusals.map((r) => {
    const consent = 'ownerConsent' in r ? (r.ownerConsent as true) : undefined
    const under = 'acceptedUnder' in r ? (r.acceptedUnder as { authorities: string[] }) : undefined
    return {
      id: `refuse-${kebab(r.name)}`,
      description: r.description,
      input: {
        raw_tx_hex: [...F.states.slice(0, r.appendAfter + 1).map((s) => s.rawTx), r.rawTx],
        ...(consent == null ? {} : { owner_consent: true }),
      },
      expected: {
        accepted: false,
        stage: 'chain',
        reason: r.error,
        ...(consent == null ? {} : { accepted_without_owner_consent: true }),
        ...(under == null ? {} : { accepted_with_authorities: under.authorities }),
      },
      tags: consent == null ? ['error-case'] : ['error-case', 'brc-42'],
    }
  })

  return {
    $schema:
      'https://raw.githubusercontent.com/bsv-blockchain/ts-stack/main/conformance/schema/vector.schema.json',
    id: 'dpp.chain.v1',
    name: 'DPP record model v1: a passport chain, its links, and the owner-signed transfer',
    brc: ['BRC-42', 'BRC-43', 'BRC-48'],
    version: '1.0.0',
    reference_impl: 'dpp-core@0.1.0',
    parity_class: 'required',
    vectors: [...stateVectors, ...ownerKeyVectors, verifyVector, ...refusalVectors],
  }
}
